spring.application.name=Quanta
spring.datasource.url=jdbc:postgresql://localhost:5432/coachingdb
spring.datasource.username=postgres
spring.datasource.password=muskan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
